version: '3'

# run Cypress tests and exit with command
#   docker-compose up --exit-code-from cypress
services:
  # this is the web application we are going to test
  sentimentalyzer:
    build: ../
    environment:
      - PORT=8080
    ports:
      - 8080:8080
  # Cypress container
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    build:
      context: ../
      dockerfile: cypress.dk
    depends_on:
      - sentimentalyzer
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://sentimentalyzer:8080
    # share the current folder as volume to avoid copying
    working_dir: /e2e
